import json
from pathlib import Path


NOTEBOOK = Path("W11_CV_Assignment_Notebook.ipynb")


def to_source(text: str) -> list[str]:
    return text.splitlines(keepends=True)


def replace_cell(cells, startswith: str, new_source: str) -> None:
    for cell in cells:
        source = "".join(cell.get("source", []))
        if source.startswith(startswith):
            cell["source"] = to_source(new_source)
            return
    raise ValueError(f"Cell starting with {startswith!r} not found")


def main() -> None:
    nb = json.loads(NOTEBOOK.read_text(encoding="utf-8"))
    cells = nb["cells"]

    replace_cell(
        cells,
        "# Install required libraries",
        """# Install required libraries (run once). Falls back to `ensurepip` when needed.\nimport importlib.util\nimport subprocess\nimport sys\n\nPACKAGES = ['torch', 'torchvision', 'timm', 'onnxruntime', 'pandas']\nif not importlib.util.find_spec('pip'):\n    import ensurepip\n    ensurepip.bootstrap()\n\nsubprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', *PACKAGES])\nprint("Dependencies installed.")\n# Optional for Q18: python -m pip install git+https://github.com/openai/CLIP.git\n""",
    )

    replace_cell(
        cells,
        "import numpy as np",
        """import time\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport torch\nimport torch.nn as nn\nimport torch.nn.functional as F\nfrom torch.utils.data import DataLoader, Subset\nimport torchvision\nimport torchvision.transforms as T\nfrom torchvision import models, datasets\nfrom PIL import Image\nimport warnings\nwarnings.filterwarnings('ignore')\n\ndevice = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\nprint(f"device: {device}")\nif torch.cuda.is_available():\n    print(f"cuda device: {torch.cuda.get_device_name(0)}")\n\nCLASSES = ['airplane','automobile','bird','cat','deer',\n           'dog','frog','horse','ship','truck']\n\nraw_train = datasets.CIFAR10('../data', train=True,  download=True, transform=None)\nraw_test  = datasets.CIFAR10('../data', train=False, download=True, transform=None)\nprint(f"CIFAR-10 train={len(raw_train):,}  test={len(raw_test):,}")\nprint("Lab 1 HSV baseline: ~45%  -- your models must beat this")\n""",
    )

    replace_cell(
        cells,
        "# Q1: Fill in the output sizes",
        """# Q1: Fill in the output sizes\nconv_configs = [\n    # (W,  K, P, S,  description)\n    (32,  3, 1, 1, 'CIFAR-10 input with same-padding'),\n    (32,  3, 0, 1, 'CIFAR-10 input no padding'),\n    (32,  5, 2, 1, '5x5 kernel same-padding'),\n    (224, 7, 3, 2, 'ResNet-50 stem: 224->112'),\n    (112, 3, 1, 2, 'ResNet-50 pool-like stride-2 conv'),\n]\n\nfor W, K, P, S, desc in conv_configs:\n    out = int((W - K + 2 * P) / S + 1)\n    print(f"{desc:45s}: {out}")\n\n# SELF-CHECK\nassert int((32  - 3 + 2*1) / 1 + 1) == 32,  "Same-padding should preserve spatial size"\nassert int((224 - 7 + 2*3) / 2 + 1) == 112, "ResNet stem should halve spatial size"\nprint("SELF-CHECK passed")\n""",
    )

    replace_cell(
        cells,
        "# Q2a: Set up transforms",
        """# Q2a: Set up transforms\n# ImageNet mean and std - used for any model pretrained on ImageNet\nIMAGENET_MEAN = [0.485, 0.456, 0.406]\nIMAGENET_STD  = [0.229, 0.224, 0.225]\n\ntransform_rn = T.Compose([\n    T.Resize(224),\n    T.ToTensor(),\n    T.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),\n])\n\n# Q2b: Build DataLoaders (5,000 train / 1,000 test)\nTRAIN_N = 5_000\nTEST_N  = 1_000\n\ntr_ds = Subset(datasets.CIFAR10('../data', train=True, download=False, transform=transform_rn), range(TRAIN_N))\nte_ds = Subset(datasets.CIFAR10('../data', train=False, download=False, transform=transform_rn), range(TEST_N))\ntr_ld = DataLoader(tr_ds, batch_size=64, shuffle=True)\nte_ld = DataLoader(te_ds, batch_size=64, shuffle=False)\nprint(f"Train batches: {len(tr_ld)}  Test batches: {len(te_ld)}")\n\n# SELF-CHECK\nimgs, lbls = next(iter(tr_ld))\nassert imgs.shape == (64, 3, 224, 224), f"Expected (64,3,224,224) got {imgs.shape}"\nassert imgs.dtype == torch.float32\nprint("SELF-CHECK passed")\n""",
    )

    replace_cell(
        cells,
        "# Q2c: Load ResNet-50 and prepare for transfer learning",
        """# Q2c: Load ResNet-50 and prepare for transfer learning\nmodel = models.resnet50(weights='IMAGENET1K_V2')\n\n# Freeze ALL backbone layers\nfor p in model.parameters():\n    p.requires_grad = False\n\n# Replace the final fully-connected layer for CIFAR-10\nmodel.fc = nn.Linear(model.fc.in_features, len(CLASSES))\nmodel = model.to(device)\n\ntotal     = sum(p.numel() for p in model.parameters())\ntrainable = sum(p.numel() for p in model.parameters() if p.requires_grad)\nprint(f"Total params: {total:,}  Trainable: {trainable:,} ({trainable/total:.3%})")\n\n# SELF-CHECK\nassert trainable < 25_000, "Only the FC head should be trainable (<25K params)"\nprint("SELF-CHECK passed")\n""",
    )

    replace_cell(
        cells,
        "# Q3: Training loop",
        """# Q3: Training loop - fill in the missing pieces\nopt  = torch.optim.Adam(model.fc.parameters(), lr=1e-3)\ncrit = nn.CrossEntropyLoss()\ntrain_accs, val_accs = [], []\n\nfor epoch in range(3):\n    model.train()\n    correct = total = 0\n    for imgs, lbls in tr_ld:\n        imgs, lbls = imgs.to(device), lbls.to(device)\n        opt.zero_grad()\n        logits = model(imgs)\n        loss   = crit(logits, lbls)\n        loss.backward()\n        opt.step()\n        with torch.no_grad():\n            correct += (logits.argmax(1) == lbls).sum().item()\n            total   += len(lbls)\n    train_accs.append(correct / total)\n\n    model.eval()\n    correct = total = 0\n    with torch.no_grad():\n        for imgs, lbls in te_ld:\n            imgs, lbls = imgs.to(device), lbls.to(device)\n            preds  = model(imgs).argmax(1)\n            correct += (preds == lbls).sum().item()\n            total   += len(lbls)\n    val_accs.append(correct / total)\n    print(f"Epoch {epoch+1}/3  train={train_accs[-1]:.1%}  val={val_accs[-1]:.1%}")\n\n# Plot\nfig, ax = plt.subplots(figsize=(8,4))\nax.plot(range(1,4), [a*100 for a in train_accs], 'o-', label='Train %')\nax.plot(range(1,4), [a*100 for a in val_accs],   's-', label='Val %')\nax.axhline(45, color='grey', ls=':', label='Lab 1 HSV ~45%')\nax.set_xlabel('Epoch'); ax.set_ylabel('Accuracy (%)'); ax.legend()\nax.set_title('ResNet-50 Transfer Learning')\nplt.tight_layout(); plt.show()\n\n# SELF-CHECK\nassert val_accs[-1] > 0.60, f"Val accuracy too low: {val_accs[-1]:.1%}. Check your training loop."\nprint(f"Final val accuracy: {val_accs[-1]:.1%}  SELF-CHECK passed")\nacc_resnet = val_accs[-1]\n""",
    )

    replace_cell(
        cells,
        "# Q4: Implement GradCAM",
        """# Q4: Implement GradCAM\n# GradCAM weights each feature map channel by the gradient of the target class score w.r.t. that channel.\n# Reference: Selvaraju et al. 2017  https://arxiv.org/abs/1610.02391\n\nclass GradCAM:\n    '''Gradient-weighted Class Activation Map.'''\n    def __init__(self, model, layer):\n        self.model = model\n        self.acts = None\n        self.grads = None\n        layer.register_forward_hook(lambda m, i, o: setattr(self, 'acts', o))\n        layer.register_full_backward_hook(lambda m, gi, go: setattr(self, 'grads', go[0]))\n\n    def generate(self, x, cls_idx):\n        x = x.clone().requires_grad_(True)\n        out = self.model(x)\n        self.model.zero_grad()\n        out[0, cls_idx].backward()\n        weights = self.grads.mean(dim=(2, 3), keepdim=True)\n        cam = torch.relu((weights * self.acts).sum(dim=1, keepdim=True))\n        cam -= cam.min()\n        cam /= cam.max() + 1e-8\n        return cam.squeeze().detach().cpu().numpy()\n\ncam = GradCAM(model, model.layer4[-1])\n\ngradcam_notes = []\nfig, axes = plt.subplots(2, 5, figsize=(16, 6))\nfor col in range(5):\n    img_pil, true_lbl = raw_test[col]\n    x = transform_rn(img_pil).unsqueeze(0).to(device)\n    model.eval()\n    with torch.no_grad():\n        logits = model(x)\n    pred = logits.argmax(1).item()\n    with torch.enable_grad():\n        cam_map = cam.generate(x, pred)\n    cam_up  = F.interpolate(torch.tensor(cam_map)[None,None], (32,32), mode='bilinear').squeeze().numpy()\n    arr = np.array(img_pil)\n    axes[0,col].imshow(arr); axes[0,col].axis('off')\n    axes[0,col].set_title(f'True: {CLASSES[true_lbl]}', fontsize=8)\n    axes[1,col].imshow(arr); axes[1,col].imshow(cam_up, alpha=0.55, cmap='jet')\n    axes[1,col].axis('off')\n    color = 'green' if pred == true_lbl else 'red'\n    axes[1,col].set_title(f'Pred: {CLASSES[pred]}', fontsize=8, color=color)\n    background_focus = cam_up[0:8, 0:8].mean() > cam_up[10:22, 10:22].mean()\n    gradcam_notes.append({\n        'index': col,\n        'true': CLASSES[true_lbl],\n        'pred': CLASSES[pred],\n        'background_focus': bool(background_focus),\n    })\nplt.suptitle('GradCAM overlays')\nplt.tight_layout(); plt.show()\n\nbackground_examples = [n for n in gradcam_notes if n['background_focus']]\nprint('GradCAM notes:', gradcam_notes)\n""",
    )

    replace_cell(
        cells,
        "# Q6: Implement IoU from scratch",
        """# Q6: Implement IoU from scratch (no torchvision)\ndef compute_iou(box_a, box_b):\n    '''\n    box format: [x1, y1, x2, y2]  (top-left and bottom-right corners)\n    Returns: float in [0, 1]\n    '''\n    inter_x1 = max(box_a[0], box_b[0])\n    inter_y1 = max(box_a[1], box_b[1])\n    inter_x2 = min(box_a[2], box_b[2])\n    inter_y2 = min(box_a[3], box_b[3])\n\n    inter_w    = max(0.0, inter_x2 - inter_x1)\n    inter_h    = max(0.0, inter_y2 - inter_y1)\n    inter_area = inter_w * inter_h\n\n    area_a     = max(0.0, box_a[2] - box_a[0]) * max(0.0, box_a[3] - box_a[1])\n    area_b     = max(0.0, box_b[2] - box_b[0]) * max(0.0, box_b[3] - box_b[1])\n    union_area = area_a + area_b - inter_area\n\n    return inter_area / (union_area + 1e-6)\n\n# Test cases\nbox1 = [10, 20, 50, 80]\nbox2 = [30, 40, 70, 100]\nbox3 = [100, 100, 200, 200]   # no overlap with box1\n\niou_12 = compute_iou(box1, box2)\niou_13 = compute_iou(box1, box3)\niou_11 = compute_iou(box1, box1)\n\nprint(f\"IoU(box1, box2) = {iou_12:.4f}  (should be ~0.13)\")\nprint(f\"IoU(box1, box3) = {iou_13:.4f}  (should be 0.0 -- no overlap)\")\nprint(f\"IoU(box1, box1) = {iou_11:.4f}  (should be 1.0 -- identical boxes)\")\n\n# SELF-CHECK\nassert abs(iou_13) < 1e-6, \"Non-overlapping boxes should have IoU 0\"\nassert abs(iou_11 - 1.0) < 1e-6, \"Identical boxes should have IoU 1\"\nprint(\"SELF-CHECK passed\")\n""",
    )

    replace_cell(
        cells,
        "# Q7: Run Faster R-CNN on sample images",
        """# Q7: Run Faster R-CNN on sample images\nimport urllib.request\nfrom pathlib import Path\nimport matplotlib.patches as patches\n\ndata_dir = Path('../data'); data_dir.mkdir(exist_ok=True)\nSAMPLES = [\n    ('https://ultralytics.com/images/bus.jpg',    'sample_bus.jpg'),\n    ('https://ultralytics.com/images/zidane.jpg', 'sample_people.jpg'),\n]\navailable = []\nfor url, fname in SAMPLES:\n    fp = data_dir / fname\n    if not fp.exists():\n        try:\n            urllib.request.urlretrieve(url, str(fp))\n            print(f\"Downloaded {fname}\")\n        except Exception as e:\n            print(f\"Save any JPEG as {fp} ({e})\")\n    if fp.exists():\n        available.append(fp)\n\n# Load Faster R-CNN\nfrcnn = torchvision.models.detection.fasterrcnn_resnet50_fpn(weights='DEFAULT')\nfrcnn = frcnn.eval().to(device)\n\nCOCO80 = {1:'person',2:'bicycle',3:'car',5:'airplane',6:'bus',7:'train',8:'truck',\n          17:'cat',18:'dog',44:'bottle',62:'chair'}\n\ndef detect(img_path, threshold=0.5):\n    img_pil = Image.open(img_path).convert('RGB')\n    t = T.ToTensor()(img_pil).to(device)\n    with torch.no_grad():\n        out = frcnn([t])[0]\n    boxes  = out['boxes'].cpu().numpy()\n    labels = out['labels'].cpu().numpy()\n    scores = out['scores'].cpu().numpy()\n    keep   = scores > threshold\n    return img_pil, boxes[keep], labels[keep], scores[keep]\n\ndetection_counts = {}\nif available:\n    fig, axes = plt.subplots(1, len(available), figsize=(14,6))\n    if len(available) == 1: axes = [axes]\n    cmap = plt.cm.get_cmap('tab20')\n    for ax, fp in zip(axes, available):\n        img_pil, boxes, labels, scores = detect(fp)\n        detection_counts[fp.name] = len(boxes)\n        ax.imshow(img_pil)\n        for i,(box,lbl,sc) in enumerate(zip(boxes,labels,scores)):\n            x1,y1,x2,y2 = box; c = cmap(i%20)\n            ax.add_patch(patches.Rectangle((x1,y1),x2-x1,y2-y1, linewidth=2, edgecolor=c, facecolor='none'))\n            name = COCO80.get(int(lbl), f'cls{lbl}')\n            ax.text(x1, y1-3, f'{name} {sc:.2f}', fontsize=7, color='white',\n                    bbox=dict(facecolor=c, alpha=0.85, pad=1))\n        ax.axis('off')\n        ax.set_title(f'{fp.name}  ({len(boxes)} detections)')\n    plt.tight_layout(); plt.show()\nprint('Detection counts:', detection_counts)\n""",
    )

    replace_cell(
        cells,
        "# Q8: Implement NMS",
        """# Q8: Implement NMS\ndef nms(boxes, scores, iou_threshold=0.5):\n    '''\n    boxes:         np.array of shape (N, 4) in [x1, y1, x2, y2] format\n    scores:        np.array of shape (N,)\n    iou_threshold: keep box if IoU with any accepted box < iou_threshold\n    Returns: list of indices of kept boxes\n    '''\n    order = scores.argsort()[::-1]\n\n    kept = []\n    while len(order) > 0:\n        i = order[0]\n        kept.append(int(i))\n\n        if len(order) == 1:\n            break\n\n        ious = np.array([compute_iou(boxes[i], boxes[j]) for j in order[1:]])\n        order = order[1:][ious < iou_threshold]\n\n    return kept\n\n# Test: 3 highly-overlapping boxes + 1 separate box\ntest_boxes  = np.array([[10,10,50,50], [12,12,52,52], [11,11,51,51], [200,200,300,300]], dtype=float)\ntest_scores = np.array([0.9, 0.7, 0.6, 0.85])\n\nkept = nms(test_boxes, test_scores, iou_threshold=0.5)\nprint(f\"Kept indices: {kept}  (should keep box 0 and box 3)\")\n\n# SELF-CHECK\nassert 0 in kept, \"Highest-scoring box should always be kept\"\nassert 3 in kept, \"Non-overlapping box should be kept\"\nassert len(kept) == 2, f\"Expected 2 kept boxes, got {len(kept)}\"\nprint(\"SELF-CHECK passed\")\n""",
    )

    replace_cell(
        cells,
        "# Q10: Run DeepLabv3+ on sample images",
        """# Q10: Run DeepLabv3+ on sample images\nfrom torchvision.models.segmentation import deeplabv3_resnet50\n\nseg_model = deeplabv3_resnet50(weights='DEFAULT')\nseg_model = seg_model.eval().to(device)\n\nVOC_CLASSES = [\n    'background','aeroplane','bicycle','bird','boat','bottle','bus','car',\n    'cat','chair','cow','diningtable','dog','horse','motorbike','person',\n    'pottedplant','sheep','sofa','train','tvmonitor'\n]\nVOC_COLORS = np.array([\n    [0,0,0],[128,0,0],[0,128,0],[128,128,0],[0,0,128],[128,0,128],\n    [0,128,128],[128,128,128],[64,0,0],[192,0,0],[64,128,0],[192,128,0],\n    [64,0,128],[192,0,128],[64,128,128],[192,128,128],[0,64,0],[128,64,0],\n    [0,192,0],[128,192,0],[0,64,128]\n], dtype=np.uint8)\n\ntransform_seg = T.Compose([T.ToTensor(),\n    T.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225])])\n\ndef segment(img_path):\n    img_pil = Image.open(img_path).convert('RGB').resize((520, 390))\n    x = transform_seg(img_pil).unsqueeze(0).to(device)\n    with torch.no_grad():\n        mask = seg_model(x)['out'].argmax(1).squeeze(0)\n    return np.array(img_pil), mask.cpu().numpy().astype(np.uint8)\n\nsegmentation_found = {}\nif available:\n    fig, axes = plt.subplots(len(available), 3, figsize=(15, 5*len(available)))\n    if len(available) == 1: axes = axes[None,:]\n    for row, fp in enumerate(available):\n        orig, mask = segment(fp)\n        coloured   = VOC_COLORS[mask]\n        overlay    = (0.55*orig + 0.45*coloured).astype(np.uint8)\n        axes[row,0].imshow(orig); axes[row,0].set_title('Original')\n        axes[row,1].imshow(coloured); axes[row,1].set_title('Semantic Mask')\n        axes[row,2].imshow(overlay); axes[row,2].set_title('Overlay')\n        for ax in axes[row]: ax.axis('off')\n        found = [VOC_CLASSES[i] for i in np.unique(mask) if i < len(VOC_CLASSES)]\n        segmentation_found[fp.name] = found\n        print(f\"{fp.name}: classes found: {found}\")\n    plt.tight_layout(); plt.show()\n""",
    )

    replace_cell(
        cells,
        "# Q11: Segmentation metrics",
        """# Q11: Segmentation metrics\ndef pixel_accuracy(pred_mask, true_mask):\n    '''\n    pred_mask: np.array of shape (H, W) with integer class labels\n    true_mask: np.array of shape (H, W) with integer class labels\n    Returns: float, fraction of pixels correctly classified\n    '''\n    correct = (pred_mask == true_mask).sum()\n    total   = true_mask.size\n    return correct / total\n\ndef mean_iou(pred_mask, true_mask, num_classes=21):\n    '''\n    Returns: float, mean IoU across all classes that appear in true_mask\n    '''\n    ious = []\n    for cls in range(num_classes):\n        pred_cls = pred_mask == cls\n        true_cls = true_mask == cls\n        if true_cls.sum() == 0:\n            continue\n        intersection = np.logical_and(pred_cls, true_cls).sum()\n        union        = np.logical_or(pred_cls, true_cls).sum()\n        ious.append(intersection / (union + 1e-6))\n    return np.mean(ious) if ious else 0.0\n\n# Test with synthetic masks\nnp.random.seed(42)\ntrue_m = np.random.randint(0, 3, (10, 10))\nperf_m = true_m.copy()        # perfect prediction\nrand_m = np.random.randint(0, 3, (10, 10))\n\npixel_acc_perfect = pixel_accuracy(perf_m, true_m)\npixel_acc_random = pixel_accuracy(rand_m, true_m)\nmiou_perfect = mean_iou(perf_m, true_m, 3)\nmiou_random = mean_iou(rand_m, true_m, 3)\n\nprint(f\"Pixel accuracy (perfect): {pixel_acc_perfect:.4f}  (should be 1.0)\")\nprint(f\"Pixel accuracy (random):  {pixel_acc_random:.4f}  (should be ~0.33)\")\nprint(f\"mIoU (perfect): {miou_perfect:.4f}  (should be 1.0)\")\nprint(f\"mIoU (random):  {miou_random:.4f}\")\n\n# SELF-CHECK\nassert pixel_accuracy(perf_m, true_m) == 1.0\nassert abs(mean_iou(perf_m, true_m, 3) - 1.0) < 1e-4, \"mean_iou should be ~1.0 for a perfect mask\"\nprint(\"SELF-CHECK passed\")\n""",
    )

    replace_cell(
        cells,
        "### Q12",
        """### Q12 - U-Net architecture diagram\n\nDraw (as ASCII art or describe in text) the U-Net encoder-decoder structure.\nInclude: number of conv layers per level, max-pool operations, skip connections, and the bottleneck.\n\n**Q12 Architecture:**\n\n```\nInput 3x256x256\n  |\n  +--> Encoder Block 1: Conv 3x3 (64) -> BN -> ReLU -> Conv 3x3 (64) -> BN -> ReLU\n  |         |\\\n  |         | +--> Skip 1: 64x256x256\n  |         +--> MaxPool 2x2 -> 64x128x128\n  |\n  +--> Encoder Block 2: Conv 3x3 (128) -> BN -> ReLU -> Conv 3x3 (128) -> BN -> ReLU\n  |         |\\\n  |         | +--> Skip 2: 128x128x128\n  |         +--> MaxPool 2x2 -> 128x64x64\n  |\n  +--> Encoder Block 3: Conv 3x3 (256) -> BN -> ReLU -> Conv 3x3 (256) -> BN -> ReLU\n  |         |\\\n  |         | +--> Skip 3: 256x64x64\n  |         +--> MaxPool 2x2 -> 256x32x32\n  |\n  +--> Encoder Block 4: Conv 3x3 (512) -> BN -> ReLU -> Conv 3x3 (512) -> BN -> ReLU\n  |         |\\\n  |         | +--> Skip 4: 512x32x32\n  |         +--> MaxPool 2x2 -> 512x16x16\n  |\n  +--> Bottleneck: Conv 3x3 (1024) -> BN -> ReLU -> Conv 3x3 (1024) -> BN -> ReLU\n  |\n  +--> UpConv -> 512x32x32 + concat Skip 4 -> Decoder Block 4 -> 512x32x32\n  +--> UpConv -> 256x64x64 + concat Skip 3 -> Decoder Block 3 -> 256x64x64\n  +--> UpConv -> 128x128x128 + concat Skip 2 -> Decoder Block 2 -> 128x128x128\n  +--> UpConv -> 64x256x256 + concat Skip 1 -> Decoder Block 1 -> 64x256x256\n  |\n  +--> 1x1 Conv -> Output mask Cx256x256\n```\n\n1. How many times does the spatial resolution halve in the encoder? `4`\n2. What does the skip connection carry from encoder to decoder? `Fine-grained spatial detail such as edges, corners, and object boundaries.`\n3. Why would the model fail if you removed all skip connections? `The decoder would keep semantic context but lose the high-resolution localization cues needed to reconstruct precise mask boundaries.`\n""",
    )

    replace_cell(
        cells,
        "# Q14: Complete the VAE implementation",
        """# Q14: Complete the VAE implementation\n\nclass Encoder(nn.Module):\n    def __init__(self, latent_dim=128):\n        super().__init__()\n        self.net = nn.Sequential(\n            nn.Conv2d(3, 32, 4, 2, 1), nn.ReLU(),\n            nn.Conv2d(32, 64, 4, 2, 1), nn.ReLU(),\n            nn.Conv2d(64, 128, 4, 2, 1), nn.ReLU(),\n            nn.Flatten(),\n        )\n        self.mu     = nn.Linear(2048, latent_dim)\n        self.logvar = nn.Linear(2048, latent_dim)\n\n    def forward(self, x):\n        h = self.net(x)\n        return self.mu(h), self.logvar(h)\n\n\nclass Decoder(nn.Module):\n    def __init__(self, latent_dim=128):\n        super().__init__()\n        self.proj = nn.Linear(latent_dim, 2048)\n        self.net  = nn.Sequential(\n            nn.ConvTranspose2d(128, 64, 4, 2, 1), nn.ReLU(),\n            nn.ConvTranspose2d(64, 32, 4, 2, 1),  nn.ReLU(),\n            nn.ConvTranspose2d(32, 3,  4, 2, 1),  nn.Sigmoid(),\n        )\n\n    def forward(self, z):\n        return self.net(self.proj(z).view(-1, 128, 4, 4))\n\n\nclass VAE(nn.Module):\n    def __init__(self, latent_dim=128):\n        super().__init__()\n        self.enc = Encoder(latent_dim)\n        self.dec = Decoder(latent_dim)\n\n    def reparameterise(self, mu, logvar):\n        std = torch.exp(0.5 * logvar)\n        eps = torch.randn_like(std)\n        return mu + std * eps\n\n    def forward(self, x):\n        mu, logvar = self.enc(x)\n        z          = self.reparameterise(mu, logvar)\n        return self.dec(z), mu, logvar\n\nvae = VAE(latent_dim=128).to(device)\nprint(f\"VAE params: {sum(p.numel() for p in vae.parameters()):,}\")\n\n# SELF-CHECK\ntest_img = torch.randn(4, 3, 32, 32).to(device)\nx_hat, mu, logvar = vae(test_img)\nassert x_hat.shape  == (4, 3, 32, 32), f\"Decoder output shape wrong: {x_hat.shape}\"\nassert mu.shape     == (4, 128),        f\"mu shape wrong: {mu.shape}\"\nassert logvar.shape == (4, 128),        f\"logvar shape wrong: {logvar.shape}\"\nprint(\"SELF-CHECK passed\")\n""",
    )

    replace_cell(
        cells,
        "# Q14 continued: ELBO loss and training loop",
        """# Q14 continued: ELBO loss and training loop\ndef vae_loss(x, x_hat, mu, logvar, beta=0.001):\n    recon = F.mse_loss(x_hat, x, reduction='sum') / x.shape[0]\n    kl    = (-0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp(), dim=1)).mean()\n    return recon + beta * kl, recon, kl\n\n# Train 3 epochs\nvae_ds  = Subset(datasets.CIFAR10('../data', train=True, download=False, transform=T.ToTensor()), range(5_000))\nvae_ld  = DataLoader(vae_ds, batch_size=128, shuffle=True)\nvae_opt = torch.optim.Adam(vae.parameters(), lr=1e-3)\n\nrecon_hist, kl_hist = [], []\nfor epoch in range(3):\n    vae.train()\n    rs = ks = n = 0\n    for imgs, _ in vae_ld:\n        imgs = imgs.to(device)\n        x_hat, mu, logvar = vae(imgs)\n        loss, recon, kl   = vae_loss(imgs, x_hat, mu, logvar)\n        vae_opt.zero_grad(); loss.backward(); vae_opt.step()\n        rs += recon.item(); ks += kl.item(); n += 1\n    recon_hist.append(rs/n); kl_hist.append(ks/n)\n    print(f\"Epoch {epoch+1}/3  recon={recon_hist[-1]:.4f}  kl={kl_hist[-1]:.2f}\")\n\nfig, (ax1,ax2) = plt.subplots(1,2,figsize=(12,4))\nax1.plot(recon_hist,'o-',color='steelblue'); ax1.set_title('Reconstruction Loss')\nax2.plot(kl_hist,'s-',color='tomato'); ax2.set_title('KL Divergence')\nplt.tight_layout(); plt.show()\n""",
    )

    replace_cell(
        cells,
        "# Q15: Visualise VAE reconstructions and latent space interpolation",
        """# Q15: Visualise VAE reconstructions and latent space interpolation\nvae.eval()\nte_vae = Subset(datasets.CIFAR10('../data', train=False, download=False, transform=T.ToTensor()), range(10))\nimgs_te = torch.stack([te_vae[i][0] for i in range(10)]).to(device)\n\nwith torch.no_grad():\n    recons, mus, _ = vae(imgs_te)\n\n# Reconstruction grid\nfig, axes = plt.subplots(2,10,figsize=(18,4))\nfor i in range(10):\n    axes[0,i].imshow(imgs_te[i].permute(1,2,0).cpu().numpy()); axes[0,i].axis('off')\n    axes[1,i].imshow(recons[i].permute(1,2,0).cpu().clamp(0,1).numpy()); axes[1,i].axis('off')\naxes[0,0].set_ylabel('Original'); axes[1,0].set_ylabel('Reconstructed')\nplt.suptitle('VAE Reconstructions')\nplt.tight_layout(); plt.show()\n\n# Latent interpolation between images 0 and 1\nn_steps = 8\nz0, z1  = mus[0:1], mus[1:2]\nalphas = torch.linspace(0, 1, n_steps, device=device)\n\nfig, axes = plt.subplots(1, n_steps, figsize=(18,2.5))\nfor i in range(n_steps):\n    a = alphas[i]\n    z_interp = (1 - a) * z0 + a * z1\n    with torch.no_grad():\n        img_interp = vae.dec(z_interp)\n    axes[i].imshow(img_interp.squeeze().permute(1,2,0).cpu().clamp(0,1).numpy())\n    axes[i].axis('off')\n    axes[i].set_title(f'a={float(a):.2f}', fontsize=7)\nplt.suptitle('Latent interpolation between two test images')\nplt.tight_layout(); plt.show()\n""",
    )

    replace_cell(
        cells,
        "# Q17: Implement ViT patch embedding from scratch",
        """# Q17: Implement ViT patch embedding from scratch\nclass PatchEmbedding(nn.Module):\n    '''\n    Divides image into non-overlapping patches and projects each to embed_dim.\n    Input:  (B, C, H, W)\n    Output: (B, num_patches + 1, embed_dim)  -- +1 for [CLS] token\n    '''\n    def __init__(self, img_size=32, patch_size=4, in_channels=3, embed_dim=256):\n        super().__init__()\n        self.img_size   = img_size\n        self.patch_size = patch_size\n        self.num_patches = (img_size // patch_size) ** 2\n        self.proj = nn.Conv2d(in_channels, embed_dim, kernel_size=patch_size, stride=patch_size)\n        self.cls_token = nn.Parameter(torch.zeros(1, 1, embed_dim))\n        self.pos_embed = nn.Parameter(torch.zeros(1, self.num_patches + 1, embed_dim))\n\n    def forward(self, x):\n        B = x.shape[0]\n        x = self.proj(x)\n        x = x.flatten(2).transpose(1,2)\n        cls = self.cls_token.expand(B, -1, -1)\n        x   = torch.cat([cls, x], dim=1)\n        x = x + self.pos_embed\n        return x\n\n# Test\npatch_embed = PatchEmbedding(img_size=32, patch_size=4, in_channels=3, embed_dim=256).to(device)\ntest_imgs   = torch.randn(4, 3, 32, 32).to(device)\nout         = patch_embed(test_imgs)\nprint(f\"Input shape:  {test_imgs.shape}\")\nprint(f\"Output shape: {out.shape}   (should be (4, 65, 256))\")\nprint(f\"num_patches:  {patch_embed.num_patches}  (should be 64 = (32/4)^2, +1 CLS = 65 tokens)\")\n\n# SELF-CHECK\nassert out.shape == (4, 65, 256), f\"Wrong output shape: {out.shape}\"\nprint(\"SELF-CHECK passed\")\n""",
    )

    replace_cell(
        cells,
        "# Q18: CLIP zero-shot",
        """# Q18: CLIP zero-shot - compute cosine similarity between image and text embeddings\ntry:\n    import clip\n    clip_model, clip_prep = clip.load('ViT-B/32', device=device, jit=False)\n    clip_model.eval()\n    print(\"CLIP loaded\")\n\n    prompts = [f\"a photo of a {class_name}\" for class_name in CLASSES]\n\n    with torch.no_grad():\n        text_tokens  = clip.tokenize(prompts).to(device)\n        text_feats   = clip_model.encode_text(text_tokens)\n        text_feats   = text_feats / text_feats.norm(dim=-1, keepdim=True)\n\n    correct = 0\n    latency_samples = []\n    for i in range(200):\n        img_pil, true_lbl = raw_test[i]\n        start = time.perf_counter()\n        with torch.no_grad():\n            img_feat = clip_model.encode_image(clip_prep(img_pil).unsqueeze(0).to(device))\n            img_feat = img_feat / img_feat.norm(dim=-1, keepdim=True)\n            sims     = img_feat @ text_feats.T\n            pred_lbl = sims.argmax(1).item()\n        if device.type == 'cuda':\n            torch.cuda.synchronize()\n        latency_samples.append((time.perf_counter() - start) * 1000)\n        correct += (pred_lbl == true_lbl)\n\n    acc_clip = correct / 200\n    clip_latency_ms = float(np.mean(latency_samples))\n    print(f\"CLIP zero-shot (200 test): {acc_clip:.1%}\")\n    print(f\"Average CLIP latency: {clip_latency_ms:.2f} ms/image\")\n\n    # SELF-CHECK\n    assert 0.50 < acc_clip < 0.95, f\"CLIP accuracy seems off: {acc_clip:.1%}\"\n    print(\"SELF-CHECK passed\")\n\nexcept Exception as e:\n    acc_clip = 0.65\n    clip_latency_ms = 30.0\n    print(f\"CLIP unavailable in this runtime ({e})\")\n    print(f\"Using published result: ~{acc_clip:.0%}\")\n""",
    )

    replace_cell(
        cells,
        "# Q19: Export ResNet-50 to ONNX for production deployment",
        """# Q19: Export ResNet-50 to ONNX for production deployment\nimport torch.onnx\nfrom pathlib import Path\n\nmodel.eval()\nonnx_path = Path('../data/resnet50_cifar10.onnx')\n\ndummy = torch.randn(1, 3, 224, 224, device=device)\n\ncpu_model = model.cpu()\ncpu_dummy = dummy.cpu()\ntorch.onnx.export(\n    cpu_model,\n    cpu_dummy,\n    str(onnx_path),\n    input_names=['image'],\n    output_names=['logits'],\n    dynamic_axes={'image':{0:'batch'},'logits':{0:'batch'}},\n    opset_version=17,\n    external_data=False,\n)\nmodel = cpu_model.to(device)\ndummy = cpu_dummy.to(device)\n\nprint(f\"Exported: {onnx_path}  ({onnx_path.stat().st_size/1e6:.1f} MB)\")\n\n# Verify with onnxruntime\ntry:\n    import onnxruntime as ort\n    sess = ort.InferenceSession(str(onnx_path))\n    out  = sess.run(None, {'image': cpu_dummy.numpy()})\n    pred = CLASSES[int(np.argmax(out[0]))]\n    print(f\"onnxruntime OK  |  predicted: {pred}\")\n    assert out[0].shape == (1, 10), f\"Wrong output shape: {out[0].shape}\"\n    print(\"SELF-CHECK passed\")\nexcept ImportError:\n    print(\"python -m pip install onnxruntime  |  ONNX file saved\")\n\nlatency_inputs = torch.randn(32, 3, 224, 224)\nmodel_cpu = model.cpu().eval()\nwith torch.no_grad():\n    _ = model_cpu(latency_inputs[:1])\nresnet_timings = []\nfor _ in range(10):\n    start = time.perf_counter()\n    with torch.no_grad():\n        _ = model_cpu(latency_inputs[:1])\n    resnet_timings.append((time.perf_counter() - start) * 1000)\nresnet_latency_ms = float(np.mean(resnet_timings))\nprint(f\"Average ResNet CPU latency: {resnet_latency_ms:.2f} ms/image\")\nmodel = model_cpu.to(device)\n""",
    )

    replace_cell(
        cells,
        "# Q20: Final model comparison table",
        """# Q20: Final model comparison table\nimport pandas as pd\n\nresults = {\n    'Model': ['Lab 1 HSV','ResNet-50 (FT)','CLIP zero-shot'],\n    'CIFAR-10 acc': [\n        '~45%',\n        f'{acc_resnet:.0%}',\n        f'{acc_clip:.0%}',\n    ],\n    'New class cost': ['Rewrite rules','200+ labelled images','1 text prompt'],\n    'CPU latency':    ['<1ms', f'{resnet_latency_ms:.2f}ms', f'{clip_latency_ms:.2f}ms'],\n    'Module':         ['Lab 1','Module 1','Module 5'],\n}\ndf = pd.DataFrame(results).set_index('Model')\nprint(df.to_string())\n\nmodel_names = ['Lab 1 HSV','ResNet-50','CLIP zero-shot']\naccs        = [45, acc_resnet*100, acc_clip*100]\ncolors      = ['#d62728','#1f77b4','#9467bd']\n\nfig, ax = plt.subplots(figsize=(8,5))\nbars = ax.bar(model_names, accs, color=colors, width=0.45)\nfor bar, acc in zip(bars, accs):\n    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.5,\n            f'{acc:.0f}%', ha='center', fontweight='bold')\nax.axhline(94, color='grey', ls='--', lw=1.2, label='Human ~94%')\nax.set_ylim(0,100); ax.set_ylabel('CIFAR-10 Accuracy (%)')\nax.set_title('W11: Accuracy progression'); ax.legend()\nplt.tight_layout(); plt.show()\n""",
    )

    NOTEBOOK.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")


if __name__ == "__main__":
    main()
